version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: pacsim-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpass
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
