services:
  postgres:
    image: postgres:17
    container_name: pacsim-postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ops
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adminpass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
