name: CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.55.0-noble
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: pacsim
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: adminpass
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: git config --global --add safe.directory /__w/pacsim/pacsim
      - name: Fetch master branch
        run: git fetch origin master:master
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - run: yarn install --immutable

      - run: npx prisma db push --schema apps/pac-shield-api/src/prisma/schema.prisma --accept-data-loss
        env:
          DATABASE_URL: postgresql://postgres:adminpass@postgres:5432/pacsim

      - name: Run affected systems
        run: |
          npx nx serve pac-shield-api &
          echo "Waiting for backend to start..."
          timeout 60 bash -c 'until curl -f http://localhost:3000/api/health; do sleep 2; done' || echo "Backend health check failed or timed out"
          npx nx affected -t lint test build e2e

        env:
          DATABASE_URL: postgresql://postgres:adminpass@postgres:5432/pacsim
      - name: Upload Playwright artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-e2e-artifacts
          path: dist/.playwright/apps/pac-shield-e2e/test-output
